### ISSUE TITLE
Problem When Compile

### ISSUE THREAD

**Issue by Dontmindmes** [Anapher/Maze#2]
https://gyazo.com/cad33e3a6570b610b35bc42d6664d019
How can i fix this? and where is build generated?

**Comment by Dontmindmes** [comment]
Script reported an error:
-> BuildFailedException: Target 'Compile Native Projects' failed.
-> One or more errors occurred. (Start of process 'powershell.exe' failed.)
-> Start of process 'powershell.exe' failed.
-> Win32Exception: The system cannot find the file specified

**Comment by Anapher** [comment]
Which operating system are you using? Do you have Powershell installed?

**Comment by Dontmindmes** [comment]
I am using windows 10 and yes i belive i do im able to open it by searching it

**Comment by Dontmindmes** [comment]
I just tried to install powershell again
and i still get this
https://gyazo.com/adbea958c7ad7ac1078fd203b501ca13

im using fake.exe run build.fsx --parallel 3 
in cmd to build

**Comment by Anapher** [comment]
Can you check if this file exists: src\modules\RemoteDesktop\prebuild.ps1

**Comment by Dontmindmes** [comment]
Yes, yes it does exist
https://gyazo.com/09a32a7b5c62db7a2acce801c3a388ca

**Comment by Dontmindmes** [comment]
I tried running cmd as admin and nothing i even tried to run it in powershell its self and nothing

**Comment by Dontmindmes** [comment]
If i run with the -v command i get this

https://gyazo.com/4b10e9d9b4a22821d5a40161bb5d76eb

**Comment by Anapher** [comment]
The issue seems to be that it cannot find powershell.exe. What happens when you press Win+R and type "powershell.exe" (and hit enter)? Does PowerShell open?

**Comment by Dontmindmes** [comment]
yes, i just tested that right now, when i do that it does inneed open up powershell
maybe a new build script could be made that allows you to put the dir to the powershell?

**Comment by Anapher** [comment]
You can try to adjust this line https://github.com/MazeAdmin/Maze/blob/master/build.fsx#L93 to set the path for powershell (just replace powershell.exe with the full path). The issue seems to be linked to your PC setup, as the build script works on my computer, my laptop and most importantly on AppVeyor.

**Comment by Dontmindmes** [comment]
Dosent work: i even tried putting powershell in the same dir as the build files and putting the dir in it but nothing, i have another computer but its clean and has nothing installed, do i have to install visual studio on it? 
https://gyazo.com/48095ffd3f9cf95fdfd2a238ae8aaf28

    CreateProcess.fromRawCommandLine "C:\Users\Master\Desktop\ProjectAlicization\Mazes\Maze\powershell.exe" <| sprintf """-NoProfile -ExecutionPolicy Bypass -File "%s" %s""" (Path.getFullName scriptPath) arguments

**Comment by Dontmindmes** [comment]
I was able to get it to work by placing the file in the same dir
https://gyazo.com/bff153d8547601b2b30fa06cfb2940c6

BUT i fell in to another problem that i dont know how to fix
https://gyazo.com/3abf22e7533e89c1d5bad5c418b2e420

**Comment by Dontmindmes** [comment]
: C:\Program Files\dotnet\sdk\2.1.700\NuGet.targets(265,5): error MSB3202: The project file "C:\Users\Mastere\Desktop\ProjectAlicization\Mazes\Maze\src\submodules\Anapher.Wpf.Toolkit\Anapher.Wpf.Toolkit\Anapher.Wpf.Toolkit.csproj" was not found.
: C:\Program Files\dotnet\sdk\2.1.700\NuGet.targets(265,5): error MSB3202: The project file "C:\Users\Mastere\Desktop\ProjectAlicization\Mazes\Maze\src\submodules\Anapher.Wpf.Toolkit\Anapher.Wpf.Toolkit.Metro\Anapher.Wpf.Toolkit.Metro.csproj" was not found.


https://gyazo.com/1ed4eab5a74f52ecf389286d35d26a93

**Comment by Dontmindmes** [comment]
I just ran it on another computer (fresh windows 10) installed everything but got the same problems

**Comment by Anapher** [comment]
Please run this command in the root of the repo:
`git submodule update --init --recursive`

**Comment by Dontmindmes** [comment]
> Script reported an error:
-> BuildFailedException: Target 'Restore Solution' failed.
-> One or more errors occurred. (Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
-> MSBuildException: Exception of type 'Fake.DotNet.MSBuildException' was thrown.

that stll happens for some reason, on both computers
but the " was not found." dosent happen anymore

**Comment by Dontmindmes** [comment]
> Script reported an error, see standard error for details.
Script reported an error:
-> BuildFailedException: Target 'Restore Solution' failed.
   StackTrace:
        at Fake.Core.TargetModule.raiseIfError(OptionalTargetContext context) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 820
        at Fake.Core.TargetModule.runOrDefault(String defaultTarget) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 936
        at <StartupCode$build_C30B26F9D130CF093EB1B348EB16004DBCE07142F79437B1821E78DE13021A25>.$Build$fsx.main@() in C:\Users\Master\Desktop\ProjectAlicization\Maze\build.fsx:line 271
-> One or more errors occurred. (Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
-> MSBuildException: Exception of type 'Fake.DotNet.MSBuildException' was thrown.
   StackTrace:
        at Fake.DotNet.MSBuild.handleAfterRun(String command, FSharpOption`1 binLogPath, Int32 exitCode, String project) in D:\a\1\s\src\app\Fake.DotNet.MSBuild\MSBuild.fs:line 751
        at Fake.DotNet.DotNet.restore(FSharpFunc`2 setParams, String project) in D:\a\1\s\src\app\Fake.DotNet.Cli\DotNet.fs:line 1058
        at Build.clo@213-33.Invoke(TargetParameter _arg7) in C:\Users\Master\Desktop\ProjectAlicization\Maze\build.fsx:line 214
        at Fake.Core.TargetModule.runSimpleInternal(TargetContext context, Target target) in D:\a\1\s\src\app\Fake.Core.Target\Target.fs:line 200

**Comment by Dontmindmes** [comment]
Also here is the other part of the error

> A fatal error occurred, the folder [C:\Users\Master\Desktop\ProjectAlicization\Maze\host\fxr] does not exist
Finished (Failed) 'DotNet:restore' in 00:00:00.3590594
Finished (Failed) 'Restore Solution' in 00:00:00.3690553

**Comment by Anapher** [comment]
Can you please open a PowerShell prompt in the root directory and execute `dotnet restore`? Btw, what is the result when you execute `dotnet --version`?

**Comment by Dontmindmes** [comment]
When i run dotnet --version i get this

> 2.1.700

**Comment by Dontmindmes** [comment]
Also even after running dotnet restore nothing happens

> Script reported an error:
-> BuildFailedException: Target 'Restore Solution' failed.
-> One or more errors occurred. (Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
-> MSBuildException: Exception of type 'Fake.DotNet.MSBuildException' was thrown.

**Comment by Dontmindmes** [comment]
> A fatal error occurred, the folder [C:\Users\Master\Desktop\ProjectAlicization\Maze\host\fxr] does not exist

**Comment by Anapher** [comment]
Yeah, you need .Net Core 3.0 (I have 3.0.100-preview5-011568 currently installed)

**Comment by Dontmindmes** [comment]
>  dotnet --version
3.0.100-preview5-011568

> ---------------------------------------------------------------------
Script reported an error:
-> BuildFailedException: Target 'Compile Native Projects' failed.
-> One or more errors occurred. (Exception of type 'Fake.DotNet.MSBuildException' was thrown.)
-> MSBuildException: Exception of type 'Fake.DotNet.MSBuildException' was thrown.


Still doesnt compile for some reason idk why, i have the latest version

**Comment by Dontmindmes** [comment]
>    "C:\Users\Providence\Desktop\ProjectAlicization\Maze\src\modules\RemoteDesktop\libraries\OpenH264net\OpenH264Lib
       .vcxproj" (default target) (1) ->
         C:\Users\Providence\Desktop\ProjectAlicization\Maze\src\modules\RemoteDesktop\libraries\OpenH264net\OpenH264Li
       b.vcxproj(29,3): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2019\Commun
       ity\MSBuild\Microsoft\VC\v160\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import>
       declaration is correct, and that the file exists on disk.

**Comment by Dontmindmes** [comment]
even with latest build this error remains
https://gyazo.com/572a415d6c549080bc964de2331f2fdf

**Comment by Anapher** [comment]
Do you have the C++ Package installed in the Visual Studio Installer?

**Comment by Dontmindmes** [comment]
Yes i have that installed too

**Comment by DecodeMehh** [comment]
> Yes i have that installed too

\Maze\src\modules\RemoteDesktop\libraries\OpenH264net
\Maze\src\modules\RemoteDesktop\libraries\x264net
Is using windows 8.1 sdk
maybe try to install it from https://developer.microsoft.com/en-us/windows/downloads/sdk-archive
<img src='https://i.imgur.com/e0ucCwo.png'>
