### ISSUE TITLE
Configuration tutorial?

### ISSUE THREAD

**Issue by Dontmindmes** [Anapher/Maze#4]
I decided just to download the latest builds you have
https://gyazo.com/69b37775be2e7b2a9595a875df9c7271

Is there a tutorial or setup process?

Server.exe
https://gyazo.com/1fcd4266d6397a877a0928b0a74f627a
https://gyazo.com/7e463f7f4650805ab8ce1251134f74ee
https://gyazo.com/8891ffc2133b95aa62dbd57360751687

**Comment by Anapher** [comment]
Please give me some time, I'm still testing and finding errors, I will publish a setup guide once it's done

**Comment by Anapher** [comment]
I did it 👍
