### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by 0x11DFE** [Anapher/Maze#5]
Hello, i have tried for hours to build Maze without any luck.
Errors i get: 
Link: x264net.obj(0,0): warning LNK4248: unresolved typeref token (0100000F) for 'x264_t'; image may not run

also WiX not supported in vs2019.
Could you please make a release of a working build?

Using VisualStudio 2019

**Comment by Suvero** [comment]
Yup, please make a release :/ I too have these issues in compile time

**Comment by Anapher** [comment]
The readme was just updated.
