### ISSUE TITLE
Runtime Error?

### ISSUE THREAD

**Issue by ChronoHELP** [Anapher/Maze#6]
So after downloading a precompiled I realized this tool doesn't load, it immediately crashes, any fixes or ideas?

**Comment by ChronoHELP** [comment]
I also completely compiled it with the same effect.

**Comment by H4xl0r** [comment]
@ChronoHELP 
How did you build ?
please post the steps and infos like version of studio and sdks fake ....
then we can go on with fixing 
i am not even able to build it

**Comment by Anapher** [comment]
The readme was just updated.
